TimelineSITE/Areas/Albums/Pages/CreateAlbum.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TimelineSITE.Data;
using TimelineSITE.Models;
using TimelineSITE.Services;


namespace TimelineSITE.Areas.Albums.Pages
{
    [Authorize(Policy = "Users")]
    public class CreateAlbumModel : PageModel
    {
        private readonly UsersDbContext _usersDbContext;
        private readonly BlobServiceClient _blobServiceClient;
        private readonly UserManager<ApplicationUser> _userManager;

        public CreateAlbumModel(UsersDbContext userDbContext, BlobServiceClient blobServiceClient, UserManager<ApplicationUser> userManager)
        {
            _usersDbContext = userDbContext;
            _blobServiceClient = blobServiceClient;
            _userManager = userManager;
        }

        [BindProperty]
        public AlbumModel Album { get; set; } = new AlbumModel();

        public IActionResult OnGet()
        {
            return Page();
        }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToPage("./Index");
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Model is not valid.");
                return Page();
            }

            using var transaction = _usersDbContext.Database.BeginTransaction();
            try
            {
                _usersDbContext.Albums.Add(Album);
                await _usersDbContext.SaveChangesAsync();

                try
                {
                    await _blobServiceClient.CreateBlobContainerAsync(Album.Id.ToString());
                }
                catch (Exception)
                {
                    ModelState.AddModelError(string.Empty, "An error occurred when creating container.");
                }

                var albumAccess = new AlbumAccessModel
                {
                    AlbumId = Album.Id,
                    UserId = (await _userManager.GetUserAsync(User)).Id,
                    ShareDate = DateTime.Now,
                    AccessLevel = AccessLevels.Owner
                };
                _usersDbContext.AlbumsAccesses.Add(albumAccess);
                await _usersDbContext.SaveChangesAsync();

                transaction.Commit();
            }
            catch (Exception)
            {
                transaction.Rollback();
            }

            return RedirectToPage("./Index");
        }
    }
}

TimelineSITE/Areas/Albums/Pages/DeleteAlbum.cshtml.cs
using Azure.Storage.Blobs;
using Azure;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using TimelineSITE.Data;
using TimelineSITE.Models;
using Microsoft.AspNetCore.Authorization;
using TimelineSITE.Areas.Albums.Services;

namespace TimelineSITE.Areas.Albums.Pages
{
    [Authorize(Policy = "Users")]
    public class DeleteAlbumModel : PageModel
    {
        private readonly UsersDbContext _usersDbContext;
        private readonly BlobServiceClient _blobServiceClient;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly AlbumPermissions _albumPermissions;

        public DeleteAlbumModel(UsersDbContext usersDbContext, BlobServiceClient blobServiceClient, UserManager<ApplicationUser> userManager, AlbumPermissions albumPermissions)
        {
            _usersDbContext = usersDbContext;
            _blobServiceClient = blobServiceClient;
            _userManager = userManager;
            _albumPermissions = albumPermissions;
        }

        [BindProperty]
        public AlbumModel Album { get; set; } = new AlbumModel();

        public async Task<IActionResult> OnGetAsync(string AlbumId)
        {
            //Set who can have access
            var requiredAccessLevels = new List<AccessLevels> { AccessLevels.Owner };
            var accessIsGranted = await _albumPermissions.CheckAlbumAccess(AlbumId, User, requiredAccessLevels);
            if (!accessIsGranted)
            {
                return RedirectToPage("./Index");
            }

            Album = await _usersDbContext.Albums.FindAsync(new Guid(AlbumId));
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //Set who can have access
            var requiredAccessLevels = new List<AccessLevels> { AccessLevels.Owner };
            var accessIsGranted = await _albumPermissions.CheckAlbumAccess(Album.Id.ToString(), User, requiredAccessLevels);
            if (!accessIsGranted)
            {
                return RedirectToPage("./Index");
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Model is not valid");
                return Page();
            }

            try
            {
                await _blobServiceClient.DeleteBlobContainerAsync(Album.Id.ToString());
                using var transaction = _usersDbContext.Database.BeginTransaction();
                try
                {
                    _usersDbContext.Albums.Remove(Album);
                    await _usersDbContext.SaveChangesAsync();
                    transaction.Commit();
                }
                catch (Exception)
                {
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, "An error occurred while deleting the album from database.");
                    return Page();
                }
            }
            catch (RequestFailedException)
            {
                ModelState.AddModelError(string.Empty, "An error occurred on request when deleting container in azure.");
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "An error occurred when deleting container in azure.");
            }

            return RedirectToPage("./Index");
        }
    }
}

TimelineSITE/Areas/Albums/Pages/EditAlbum.cshtml.cs
using Azure.Storage.Blobs;
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TimelineSITE.Data;
using System.ComponentModel.DataAnnotations;
using TimelineSITE.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using TimelineSITE.Areas.Albums.Services;

namespace TimelineSITE.Areas.Albums.Pages
{
    [Authorize(Policy = "Users")]
    public class EditAlbumModel : PageModel
    {
        private readonly UsersDbContext _usersDbContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly AlbumPermissions _albumPermissions;

        public EditAlbumModel(UsersDbContext usersDbContext, UserManager<ApplicationUser> userManager, AlbumPermissions albumPermissions)
        {
            _usersDbContext = usersDbContext;
            _userManager = userManager;
            _albumPermissions = albumPermissions;
        }

        [BindProperty]
        public AlbumModel Album { get; set; } = new AlbumModel();

        public async Task<IActionResult> OnGetAsync(string AlbumId)
        {
            //Set who can have access
            var requiredAccessLevels = new List<AccessLevels> { AccessLevels.Owner };
            var accessIsGranted = await _albumPermissions.CheckAlbumAccess(AlbumId, User, requiredAccessLevels);
            if (!accessIsGranted)
            {
                return RedirectToPage("./Index");
            }

            Album = await _usersDbContext.Albums.FindAsync(new Guid(AlbumId));
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //Set who can have access
            var requiredAccessLevels = new List<AccessLevels> { AccessLevels.Owner };
            var accessIsGranted = await _albumPermissions.CheckAlbumAccess(Album.Id.ToString(), User, requiredAccessLevels);
            if (!accessIsGranted)
            {
                return RedirectToPage("./Index");
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Model is not valid");
                return Page();
            }

            using var transaction = _usersDbContext.Database.BeginTransaction();
            try
            {
                var albumToEdit = await _usersDbContext.Albums.FindAsync(Album.Id);
                albumToEdit.Name = Album.Name;
                albumToEdit.DateStart = Album.DateStart;
                albumToEdit.DateEnd = Album.DateEnd;
                await _usersDbContext.SaveChangesAsync();
                transaction.Commit();
            }
            catch (Exception)
            {
                transaction.Rollback();
                ModelState.AddModelError(string.Empty, "An error occurred while deleting the album from database.");
                return Page();
            }

            return RedirectToPage("./PhotoAlbum", new { AlbumId = Album.Id });
        }
    }
}

TimelineSITE/Areas/Albums/Pages/Index.cshtml.cs
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static TimelineSITE.Areas.Manage.Pages.Roles.IndexModel;
using TimelineSITE.Models;
using TimelineSITE.Data;
using System.Data;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using static TimelineSITE.Areas.Albums.Pages.ShareAlbumModel;
using Microsoft.AspNetCore.Authorization;

namespace TimelineSITE.Areas.Albums.Pages
{
    [Authorize(Policy = "Users")]
    public class IndexModel : PageModel
    {
        private readonly UsersDbContext _usersDbContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel( UsersDbContext usersDbContext, UserManager<ApplicationUser> userManager)
        {
            _usersDbContext = usersDbContext;
            _userManager = userManager;
        }
        
        [BindProperty]
        public List<AlbumAccessModel> AlbumsAccessList { get; private set; } = new List<AlbumAccessModel>();

        public async Task<IActionResult> OnGetAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            AlbumsAccessList = await _usersDbContext.AlbumsAccesses.Where(u=>u.UserId==user.Id).Include(aa => aa.Album).ToListAsync();
            
            return Page();
        }
    }
}

TimelineSITE/Areas/Albums/Pages/ShareAlbum.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using TimelineSITE.Areas.Albums.Services;
using TimelineSITE.Data;
using TimelineSITE.Models;

namespace TimelineSITE.Areas.Albums.Pages
{
    [Authorize(Policy = "Users")]
    public class ShareAlbumModel : PageModel
    {
        private readonly UsersDbContext _usersDbContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly AlbumPermissions _albumPermissions;

        public ShareAlbumModel(UsersDbContext usersDbContext, UserManager<ApplicationUser> userManager, AlbumPermissions albumPermissions)
        {
            _usersDbContext = usersDbContext;
            _userManager = userManager;
            _albumPermissions = albumPermissions;
        }

        [BindProperty]
        public AlbumModel Album { get; set; } = new AlbumModel();

        [BindProperty]
        public List<AlbumAccessModel> SharedUsersList { get; set; } = new List<AlbumAccessModel>();

        private async Task LoadDataAsync(AlbumModel album)
        {
            SharedUsersList = await _usersDbContext.AlbumsAccesses
           .Where(aa => aa.AlbumId == album.Id).Include(u => u.User)
           .ToListAsync();
        }

        public async Task<IActionResult> OnGetAsync(string AlbumId)
        {
            //Set who can have access
            var requiredAccessLevels = new List<AccessLevels> { AccessLevels.Owner };
            var accessIsGranted = await _albumPermissions.CheckAlbumAccess(AlbumId, User, requiredAccessLevels);
            if (!accessIsGranted)
            {
                return RedirectToPage("./Index");
            }

            Album = await _usersDbContext.Albums.FindAsync(new Guid(AlbumId));
            await LoadDataAsync(Album);
            return Page();
        }

        public async Task<IActionResult> OnPostShare(string email, AccessLevels accesslevel)
        {
            //Set who can have access
            var requiredAccessLevels = new List<AccessLevels> { AccessLevels.Owner };
            var accessIsGranted = await _albumPermissions.CheckAlbumAccess(Album.Id.ToString(), User, requiredAccessLevels);
            if (!accessIsGranted)
            {
                return RedirectToPage("./Index");
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Model is not valid");
                await LoadDataAsync(Album);
                return Page();
            }

            var userToShare = await _userManager.FindByEmailAsync(email);
            if (userToShare == null)
            {
                ModelState.AddModelError("", "Email does not exist in database");
                await LoadDataAsync(Album);
                return Page();
            }

            try
            {
                var newAlbumAccess = new AlbumAccessModel
                {
                    UserId = userToShare.Id,
                    AlbumId = Album.Id,
                    ShareDate = DateTime.Now,
                    AccessLevel = accesslevel
                };
                _usersDbContext.AlbumsAccesses.Add(newAlbumAccess);
                await _usersDbContext.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                if (ex.InnerException is SqlException sqlException && sqlException.Number == 2601)
                {
                    ModelState.AddModelError(string.Empty, "The share with given email arleady exist in database");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "An error occurred while adding the album access to database.");
                }
            }

            await LoadDataAsync(Album);
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAccess(string albumaccessid)
        {
            //Set who can have access
            var requiredAccessLevels = new List<AccessLevels> { AccessLevels.Owner };
            var accessIsGranted = await _albumPermissions.CheckAlbumAccess(Album.Id.ToString(), User, requiredAccessLevels);
            if (!accessIsGranted)
            {
                return RedirectToPage("./Index");
            }
            var albumAccessToDelete = await _usersDbContext.AlbumsAccesses.FirstOrDefaultAsync(aa => aa.Id.ToString() == albumaccessid);
            if (albumAccessToDelete == null)
            {
                return RedirectToPage("./Index");
            }
            if ((await _userManager.GetUserAsync(User)).Id.ToString() == albumAccessToDelete.UserId)
            {
                ModelState.AddModelError("", "You cannot delete your own access");
                await LoadDataAsync(Album);
                return Page();
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Model is not valid");
                await LoadDataAsync(Album);
                return Page();
            }

            try
            {
                _usersDbContext.AlbumsAccesses.Remove(albumAccessToDelete);
                await _usersDbContext.SaveChangesAsync();
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while deleting the album access from database.");
            }

            await LoadDataAsync(Album);
            return Page();
        }
    }
}

TimelineSITE/Areas/Albums/Pages/CreateAlbum.cshtml
@page
@model TimelineSITE.Areas.Albums.Pages.CreateAlbumModel

@{
    ViewData["Title"] = "Create Album";
}

<h2>@ViewData["Title"]</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div class="form-floating">
                <input asp-for="Album.Name" class="form-control" aria-required="true">
                <label asp-for="Album.Name" class="form-label"></label>
                <span asp-validation-for="Album.Name" class="text-danger"></span>
            </div>
            <div class="form-floating">
                <input asp-for="Album.DateStart" class="form-control" aria-required="false">
                <label asp-for="Album.DateStart" class="form-label"></label>
                <span asp-validation-for="Album.DateStart" class="text-danger"></span>
            </div>
            <div class="form-floating">
                <input asp-for="Album.DateEnd" class="form-control" aria-required="false">
                <label asp-for="Album.DateEnd" class="form-label"></label>
                <span asp-validation-for="Album.DateEnd" class="text-danger"></span>
            </div>
            <div class="row pt-2">
                <div class="col pe-1">
                    <button type="submit" class="btn btn-danger w-100">Create Album</button>
                </div>
                <div class="col ps-1">
                    <a class="btn btn-primary w-100" asp-page="Index">Cancel</a>
                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TimelineSITE/Areas/Albums/Pages/DeleteAlbum.cshtml
@page "/Albums/{albumId}/Delete"
@model TimelineSITE.Areas.Albums.Pages.DeleteAlbumModel
@{
    ViewData["Title"] = "Delete Album";
}
<h2>Are you sure you want delete this album</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <input type="hidden" asp-for="@Model.Album.Id" />
            <input type="hidden" asp-for="@Model.Album.Name" />
            <div class="form-floating">
                <input asp-for="@Model.Album.Name" class="form-control" disabled />
                <label asp-for="@Model.Album.Name" class="form-label"></label>
            </div>
            <div class="form-floating">
                <input asp-for="@Model.Album.DateStart" class="form-control" disabled />
                <label asp-for="@Model.Album.DateStart" class="form-label"></label>
            </div>
            <div class="form-floating">
                <input asp-for="@Model.Album.DateEnd" class="form-control" disabled />
                <label asp-for="@Model.Album.DateEnd" class="form-label"></label>
            </div>
            <div class="row pt-2">
                <div class="col pe-1">
                    <button type="submit" class="w-100 btn btn-danger">Yes! Delete</button>
                </div>
                <div class="col ps-1">
                    <a class="btn btn-primary w-100" asp-area="Albums" asp-page="/PhotoAlbum" asp-route-AlbumId="@Model.Album.Id">Cancel</a>
                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </form>
    </div>
</div>

TimelineSITE/Areas/Albums/Pages/EditAlbum.cshtml
@page "/Albums/{AlbumId}/Edit"
@model TimelineSITE.Areas.Albums.Pages.EditAlbumModel
@{
    ViewData["Title"] = "Edit Album";
}
<h2>@ViewData["Title"]</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <input type="hidden" asp-for="@Model.Album.Id" />
            <div class="form-floating">
                <input asp-for="@Model.Album.Name" class="form-control" />
                <label asp-for="@Model.Album.Name" class="form-label"></label>
            </div>
            <div class="form-floating">
                <input asp-for="@Model.Album.DateStart" class="form-control" />
                <label asp-for="@Model.Album.DateStart" class="form-label"></label>
            </div>
            <div class="form-floating">
                <input asp-for="@Model.Album.DateEnd" class="form-control" />
                <label asp-for="@Model.Album.DateEnd" class="form-label"></label>
            </div>
            <div class="row pt-2">
                <div class="col pe-1">
                    <button type="submit" class="w-100 btn btn-danger">Confirm</button>
                </div>
                <div class="col ps-1">
                    <a class="btn btn-primary w-100" asp-area="Albums" asp-page="/PhotoAlbum" asp-route-AlbumId="@Model.Album.Id">Cancel</a>
                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </form>
    </div>
</div>

TimelineSITE/Areas/Albums/Pages/Index.cshtml
@page
@model TimelineSITE.Areas.Albums.Pages.IndexModel
@{
    ViewData["Title"] = "Albums";
}
<div class="row justify-content-between align-items-center">
    <h2 class="col-auto mr-auto">@ViewData["Title"]</h2>
    <div class="col-auto content"><a class="btn btn-primary" asp-area="Albums" asp-page="/CreateAlbum">Create Album</a></div>
</div>
<hr />

<div class="album-gallery">
    @foreach (var albumAccess in Model.AlbumsAccessList)
    {
        <div class="album-box">
            <a class="btn btn-primary" asp-area="Albums" asp-page="/PhotoAlbum" asp-route-AlbumId="@albumAccess.Album.Id">
                <div class="album-content">
                    <p class="journey-date">
                        @if (albumAccess.Album.DateStart != null)
                        {
                            @albumAccess.Album.DateStart.Value.ToString("dd.MM.yyyy");
                        }
                        @if (albumAccess.Album.DateStart != null && albumAccess.Album.DateEnd != null)
                        {
                            @Html.Raw(" - ")
                        }
                        @if (albumAccess.Album.DateEnd != null)
                        {
                            @albumAccess.Album.DateEnd.Value.ToString("dd.MM.yyyy");
                        }
                    </p>
                    <div class="folder-icon">
                        @if (albumAccess.AccessLevel == TimelineSITE.Models.AccessLevels.Owner)
                        {
                            <span class="bi bi-folder-fill" style="font-size: 50px;"></span>
                        }
                        @if (albumAccess.AccessLevel == TimelineSITE.Models.AccessLevels.Guest)
                        {
                            <span class="bi bi-folder" style="font-size: 50px;"></span>
                        }
                        @if (albumAccess.AccessLevel == TimelineSITE.Models.AccessLevels.ViewOnly)
                        {
                            <span class="bi bi-folder-symlink" style="font-size: 50px;"></span>
                        }
                    </div>
                    <div class="album-text w-100">
                    <h5 >@albumAccess.Album.Name</h5>
                    </div>
                </div>
            </a>
        </div>
    }
</div>

TimelineSITE/Areas/Albums/Pages/PhotoAlbum.cshtml
@page "/Albums/{AlbumId}"
@using Microsoft.AspNetCore.Identity
@inject UserManager<TimelineSITE.Models.ApplicationUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
    var accessLevel = Model.Album.UsersAccess.FirstOrDefault(u => u.UserId == user.Id).AccessLevel;
}
@model TimelineSITE.Areas.Albums.Pages.PhotoAlbumModel
@{
    ViewData["Title"] = Model.Album.Name;
}
<div class="row justify-content-between align-items-center">
    <div class="col mr-auto">
        <row><h2 class="mb-0 text-truncate">@ViewData["Title"]</h2></row>
        <row>
            <small class="text-muted mb-0">
                @if (Model.Album.DateStart != null)
                {
                    @Model.Album.DateStart.Value.ToString("dd.MM.yyyy")
                    ;
                }
                @if (Model.Album.DateStart != null && Model.Album.DateEnd != null)
                {
                    @Html.Raw(" - ")
                }
                @if (Model.Album.DateEnd != null)
                {
                    @Model.Album.DateEnd.Value.ToString("dd.MM.yyyy")
                    ;
                }
            </small>
        </row>
    </div>
    <div class="col-auto content">
        <div class="d-flex flex-row align-items-center">
            @if (accessLevel == TimelineSITE.Models.AccessLevels.Owner || accessLevel == TimelineSITE.Models.AccessLevels.Guest)
            {
                <div class="select-all m-1">
                    <input type="checkbox" id="selectAll"> Select All
                </div>
                <button class="m-1 btn btn-primary" id="deleteAll">
                    Delete Selected
                </button>
                <div class="m-1 badge bg-secondary" style="display: none;" id="uploadCounter"><span id="uploadedCount">0</span> / <span id="totalCount">0</span></div>
                <label for="fileInput" class="m-1 btn btn-primary">
                    <form method="POST" enctype="multipart/form-data" id="uploadForm">
                        <input type="hidden" name="AlbumId" value="@Model.Album.Id" id="albumIdInput" />
                        <input type="file" name="UploadedFile" class="form-control-file" id="fileInput" style="display: none;" multiple />
                        Upload
                    </form>
                </label>
            }
            @if (accessLevel == TimelineSITE.Models.AccessLevels.Owner)
            {
                <button class="1-2 btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    Manage Album
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <a class="dropdown-item" asp-area="Albums" asp-page="/ShareAlbum" asp-route-AlbumId="@Model.Album.Id">Share Album</a>
                    <a class="dropdown-item" asp-area="Albums" asp-page="/EditAlbum" asp-route-AlbumId="@Model.Album.Id">Edit Album</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-area="Albums" asp-page="/DeleteAlbum" asp-route-AlbumId="@Model.Album.Id">Delete Album</a>
                </div>
            }
        </div>
    </div>
</div>
<div id="uploadStatus"></div>
<hr />
<div class="photo-gallery">
    @foreach (var image in Model.Images)
    {
        <div class="photo-box">
            @if (accessLevel == TimelineSITE.Models.AccessLevels.Owner || accessLevel == TimelineSITE.Models.AccessLevels.Guest)
            {
                <input type="checkbox" class="photo-checkbox" data-id="@image.Image.Id">
            }
            @if (@image.Image.ContentType.StartsWith("video/"))
            {
                <span class="photo-play bi bi-play-circle"></span>
            }
            <img src="data:image/jpeg;base64,@Convert.ToBase64String(image.Image.ThumbnailImage)" type="@image.Image.ContentType" />
            <a href="@image.Url"></a>
        </div>
    }
</div>

<div class="expanded-view" tabindex=" 0">
    <button class="btn btn-dark close-button">&times;</button>
    <img src="" alt="Expanded Image">
    <video controls autoplay>
        <source src="" type="video/mp4">
        Your browser does not support the video tag.
    </video>
    <button class="btn btn-dark btn-lg prev-button">&lt;</button>
    <button class="btn btn-dark btn-lg next-button">&gt;</button>
</div>

@section Scripts {
    <script src="~/js/ExpandImageViewer.js"></script>
    <script src="~/js/AutomatedUploadingFiles.js"></script>
    <script src="~/js/DeleteSelectedFiles.js"></script>
}

TimelineSITE/Areas/Albums/Pages/ShareAlbum.cshtml
@page "/Albums/{AlbumId}/Share"
@model TimelineSITE.Areas.Albums.Pages.ShareAlbumModel
@{
    ViewData["Title"] = "Share Album";
}
<h2>@ViewData["Title"] &#x2022; @Model.Album.Name</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-page-handler="Share" method="post">
            <input type="hidden" asp-for="@Model.Album.Id" />
            <input type="hidden" asp-for="@Model.Album.Name" />
            <div class="form-floating">
                <input type="text" name="email" class="form-control" />
                <label class="form-label">Email</label>
            </div>
            <div class="form-group">
                <label class="form-label">Access Level</label>
                <select type="text" name="accesslevel" class="form-control">
                    @foreach (var accessLevel in Enum.GetValues(typeof(TimelineSITE.Models.AccessLevels)))
                    {
                        <option value="@((int)accessLevel)">@accessLevel</option>
                    }
                </select>
            </div>
            <div class="row pt-2">
                <div class="col pe-1">
                    <button type="submit" class="w-100 btn btn-danger">Add</button>
                </div>
                <div class="col ps-1">
                    <a class="btn btn-primary w-100" asp-area="Albums" asp-page="/PhotoAlbum" asp-route-AlbumId="@Model.Album.Id">Cancel</a>
                </div>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </form>
    </div>
    <div class="col-md-8">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Shared Date</th>
                    <th>Access Level</th>
                    <th>Manage</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var access in Model.SharedUsersList)
                {
                    <tr>
                        <td>@access.User.Email</td>
                        <td>@access.ShareDate</td>
                        <td>@access.AccessLevel</td>
                        <td>
                            <form asp-page-handler="DeleteAccess" method="post">
                                <input type="hidden" asp-for="@Model.Album.Id" />
                                <input type="hidden" asp-for="@Model.Album.Name" />
                                <input type="hidden" name="albumaccessid" value="@access.Id" />
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>